sphinx:
	sphinx-apidoc -Pfe -o docs rcluster
	sphinx-build -E -b html docs docs/_build

built:
	rm -f dist/*
	python setup.py sdist
	python setup.py bdist_wheel

git:
	git add --all
	if git --no-pager diff HEAD ; then \
	echo "Please type commit message:" ; \
	read commit_message ; \
	git commit -m "$$commit_message"; fi ;

test:
	@py.test

practice: test sphinx built git

publish: practice
	git push origin master
	twine upload dist/*
	python setup.py upload_sphinx
