sphinx:
	sphinx-apidoc -Pfe -o docs rcluster
	sphinx-build -E -b html docs docs/_build

built:
	python setup.py sdist
	python setup.py bdist_wheel

git:
	git add --all
	git --no-pager diff HEAD
	@echo "Please type commit message:"
	@read commit_message;\
	git commit -m "$$commit_message"

publish: sphinx built git
	git push origin master
	twine upload dist/*
	python setup.py upload_sphinx
